// <auto-generated />
using System;
using Bugs.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bugs.Migrations
{
    [DbContext(typeof(BugsContext))]
    partial class BugsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Bugs.Models.BugModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Description");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("BugModel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("665c4b6e-4e13-427c-85af-c3881d54c4f4"),
                            Description = "no Image",
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("79de8c49-e0e5-4fd0-b238-84a16a63e26f"),
                            Description = "no price",
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("a39d188d-5925-4690-9669-90a6f98ca2cc"),
                            Description = "no name",
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("762f327b-4d7f-46cc-aea0-4ba213da9eed"),
                            Description = "no descriptive text",
                            Status = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
